---

- name: create a new droplet
  digital_ocean_droplet:
    state: present
    name: "{{ droplet_name }}"
    size: "{{ droplet_size }}"
    region: "{{ droplet_region }}"
    image: ubuntu-18-04-x64
    wait_timeout: 500
    monitoring: yes
    unique_name: yes
    ssh_keys: 27319103
  register: do

- name: printing variable
  debug:
    var: do.data.ip_address

- name: Add new host to our inventory.
  add_host:
    name: "{{ do.data.ip_address }}"
    groups: digital_ocean_host
  when: do.data.droplet is defined
  changed_when: False

- name: Update local hosts file
  template: 
    src: hosts.ini.j2
    dest: ./hosts.ini
