---

  # The initial set of commands target localhost - these are used to talk to
  # the DigitalOcean API to create a new droplet.

- hosts: localhost
  connection: local
  gather_facts: False

  vars_files:
    - group_vars/all.yml

  roles:
    - create-new-droplet

  # Now we need to wait for the server to become ready

- hosts: digital_ocean_host
  remote_user: root
  gather_facts: False

  vars_files:
    - group_vars/all.yml

  roles:
    - wait-for-droplet-to-be-ready

  # The following commands provision the droplet to run our game server. The 
  # host was dynamically filled by the earlier commands.

- hosts: digital_ocean_host
  remote_user: root
  gather_facts: True

  vars_files:
    - group_vars/all.yml

  roles:
    - create-user-account
    - setup-dropbox
    - install-mono-and-dependencies
    - download-game-server-and-mods



