---
- hosts: localhost
  connection: local
  gather_facts: False

  tasks:

    - name: remove/delete droplet
      digital_ocean_droplet:
        state: absent
        name: terraria-server-swan-01
        size: s-2vcpu-4gb
        region: ams3
        image: ubuntu-18-04-x64
        wait_timeout: 500
        monitoring: yes
        unique_name: yes
        ssh_keys: 27319103

