---

- hosts: gameserver
  remote_user: root
  gather_facts: True

  vars_files:
    - group_vars/all.yml

  roles:
    - save-gameworld


- hosts: localhost
  connection: local
  gather_facts: False

  vars_files:
    - group_vars/all.yml

  roles:
    - delete-droplet
