---
- hosts: localhost
  connection: local
  gather_facts: False

  tasks:

    - name: create a new droplet
      digital_ocean_droplet:
        state: present
        name: mydroplet
        size: 2gb
        region: ams3
        image: centos-7-x64
        wait_timeout: 500
        monitoring: yes
        unique_name: yes
        ssh_keys: 27319103
      register: do

    - name: printing variable
      debug:
        var: do.data.ip_address

    - name: Add new host to our inventory.
      add_host:
        name: "{{ do.data.ip_address }}"
        groups: just_created
      when: do.data.droplet is defined
      changed_when: False



- hosts: just_created
  remote_user: root
  gather_facts: False

  tasks:
    - name: Wait for port 22 to become available.
      local_action: "wait_for port=22 host={{ inventory_hostname }}"

    - name: ping
      ping:

