---

- name: update apt cache
  apt:
    update_cache: yes  

- name: Install required system packages
  apt:
    state: present
    name: [
      'apt-transport-https', 
      'ca-certificates', 
      'curl', 
      'software-properties-common',
      'python3-pip', 
      'virtualenv', 
      'python3-setuptools'
    ]

- name: ensure Docker repository key is installed
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: ensure docker repository is available
  apt_repository: 
    repo: 'deb https://download.docker.com/linux/ubuntu bionic stable' 
    state: present

- name: ensure docker and dependencies are installed
  apt: 
    name: docker-ce 
    update_cache: yes

- name: Restart the service    
  service: 
    name: docker 
    state: restarted

- name: Install python requirements to build docker
  pip:
    name:
      - docker


